### ISSUE TITLE
HTTP Server plugins issue

### ISSUE THREAD

**Issue by haytxy** [centreon/centreon-plugins#4540]
hello Guys,

Any idea how to approach this issue?

plugin:
https://docs.centreon.com/pp/integrations/plugin-packs/procedures/applications-protocol-http/

After I run
 /usr/lib/centreon/plugins//centreon_protocol_http.pl --plugin=apps::protocols::http::plugin --mode=json-content --hostname=10.140.140.105 --proto='http' --port='80'  --urlpath='/xx/xx/monitors.json' --header='Content-Type: text/xml' --data='' --lookup='' --threshold-value='count' --format-ok='%{count} element(s) found' --format-warning='%{count} element(s) found' --format-critical='%{count} element(s) found'  --warning-numeric='' --critical-numeric='' --warning-string='' --critical-string='' 

 I get this error 
Status information
UNKNOWN: Cannot load module --mode.
Could not find sub '$TOKEN_ROOT' exported by JSON::Path::Constants at /usr/local/share/perl5/JSON/Path/Evaluator.pm line 11.
BEGIN failed--compilation aborted at /usr/local/share/perl5/JSON/Path/Evaluator.pm line 11.
Compilation failed in require at /usr/local/share/perl5/JSON/Path.pm line 14.
BEGIN failed--compilation aborted at /usr/local/share/perl5/JSON/Path.pm line 14.
Compilation failed in require at /usr/lib/centreon/plugins//centreon_protocol_http.pl line 2301.
BEGIN failed--compilation aborted at /usr/lib/centreon/plugins//centreon_protocol_http.pl line 2301.
Compilation failed in require at /usr/lib/centreon/plugins//centreon_protocol_http.pl line 5449.
 

When Im trying run this plugin from CLI it looks like that:
![image](https://github.com/centreon/centreon-plugins/assets/79607995/b869bc04-cf74-472d-a289-b58b1fa73bd3)

Marcin

**Comment by garnier-quentin** [comment]
How have you installed the dependency (JSON::Path) ? It looks like a manual install.

**Comment by haytxy** [comment]
The only thing I did it was these two steps . 
![image](https://github.com/centreon/centreon-plugins/assets/79607995/bb0d0e43-8fb7-4165-a26f-de0ffa7e954f)

Do I need to install something more?

**Comment by garnier-quentin** [comment]
What is your JSON::Path package version ?

**Comment by haytxy** [comment]
hi @garnier-quentin  

package JSON::Path;
$JSON::Path::VERSION = '1.0.3';

Centreon 23.04.4

m

**Comment by haytxy** [comment]
Here I tried to run hello command.
Could someone confirm that this plugin works on Centreon 23.04.4 ?

Curent setup:
Centreon 23.04.4
Oracle Linux Server 8.8
Linux 5.15.0-102.110.5.1.el8uek.x86_64

/usr/lib/centreon/plugins//centreon_protocol_http.pl \
    --plugin=apps::protocols::http::plugin \
    --mode=json-content \
	--help

![image](https://github.com/centreon/centreon-plugins/assets/79607995/1bc71a49-c867-4ad7-9da6-2314b38c91e0)

**Comment by ponchoh** [comment]
https://thewatch.centreon.com/data-collection-6/centreon-plugin-error-http-server-2014

**Comment by garnier-quentin** [comment]
It's done you can downgrade the JSON Path rpm to use the version 0.5
